title: 技術情報おおいた
description: 大分県産業科学技術センター 技術情報誌
url: "https://tiny-otter-996358.netlify.app"
baseurl: ""
lang: ja

plugins:
  - jekyll-feed

permalink: /news/:year/:month/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
